#[repr(C)]
pub struct HdaRegisters {
    pub gcap: u16,
    pub vmin: u8,
    pub vmaj: u8,
    pub outpay: u16,
    pub inpay: u16,
    pub gctl: u32,
    pub wakeen: u16,
    pub statests: u16,
    pub gsts: u16,
    _rsvd0: u16,
    pub outstrmpay: u16,
    pub instrmpay: u16,
    pub intctl: u32,
    pub intsts: u32,
    pub walclk: u32,
    pub ssync: u32,
    pub corblbase: u32,
    pub corbubase: u32,
    pub corbwp: u16,
    pub corbrp: u16,
    pub corbctl: u8,
    pub corbsts: u8,
    pub corbsize: u8,
    _rsvd1: u8,
    pub rirblbase: u32,
    pub rirbubase: u32,
    pub rirbwp: u16,
    pub rirbctl: u8,
    pub rirbsts: u8,
    pub rirbsize: u8,
    _rsvd2: u8, //apparantly this is how u pad in rust
    pub icoi: u32,
    pub icii: u32,
    pub icis: u32,
    pub dplbase: u32,
    pub dpubase: u32,
    _rsvd3: [u8; 0x80 - 0x5C],
    pub stream_regs: [StreamDescriptor; 30],
}

#[repr(C)]
pub struct StreamDescriptor {
    pub ctl: u32,
    pub sts: u32,
    pub lpib: u32,
    pub cbl: u32,
    pub lvi: u16,
    pub reserved: u16,
    pub fmt: u16,
    pub reserved2: u16,
    pub bdlpl: u32,
    pub bdlpu: u32,
}