#[repr(C)]
pub struct HdaRegisters {
    pub gcap: u16,
    pub vmin: u8,
    pub vmaj: u8,
    pub outpay: u16,
    pub inpay: u16,
    pub gctl: u32,
    pub wakeen: u16,
    pub statests: u16,
    pub gsts: u16,
    pub _pad: [u8; 6],
    pub outstrmpay: u16,
    pub instrmpay: u16,
    pub _pad1: [u8; 4],
    pub intctl: u32,
    pub intsts: u32,
    pub _pad2: [u8; 8],
    pub walclk: u32,
    pub _pad3: u32,
    pub ssync: u32,
    pub _pad4: u32,
    pub corblbase: u32,
    pub corbubase: u32,
    pub corbwp: u16,
    pub corbrp: u16,
    pub corbctl: u8,
    pub corbsts: u8,
    pub corbsize: u8,
    pub _pad5: u8,
    pub rirblbase: u32,
    pub rirbubase: u32,
    pub rirbwp: u16,
    pub rintcnt: u16,
    pub rirbctl: u8,
    pub rirbsts: u8,
    pub rirbsize: u8,
    pub _pad6: u8,
    pub icoi: u32,
    pub icii: u32,
    pub icis: u32,
    pub _pad7: u32,
    pub dplbase: u32,
    pub dpubase: u32,
    pub _pad8: [u8; 8],
    pub stream_regs: [StreamDescriptor; 30],
}

#[repr(C)]
pub struct StreamDescriptor {
    pub ctl0: u8,
    pub ctl1: u8,
    pub ctl2: u8,
    pub sts: u8,
    pub lpib: u32,
    pub cbl: u32,
    pub lvi: u16,
    pub _pad: u16,
    pub fifo: u16,
    pub fmt: u16,
    pub _pad1: u32,
    pub bdlpl: u32,
    pub bdlpu: u32,
}
