[package]
name = "taos"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
limine = "0.3.1"
spin = "0.9.8"
uart_16550 = "0.3.2"
x86_64 = "0.15.2"
